apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ds-demo
  template:
    metadata:
      labels:
        app: ds-demo
    spec:
      containers:
      - name: ds-demo
        image: ds-k8s-demo:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Never   # important: tells K8s to use your local image